export const REPLACE_STATE = "REPLACE_STATE";
export const CLEAR_FORM = "CLEAR_FORM";
export const UPDATE_STATE_KEY = "UPDATE_STATE_KEY";
export const UPDATE_STATE_OBJECT_KEY = "UPDATE_STATE_OBJECT_KEY";
export const ADD_LIST_ITEM = "ADD_LIST_ITEM";
export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM";
export const UPDATE_LIST_ITEM_OBJECT_KEY = "UPDATE_LIST_ITEM_OBJECT_KEY";
export const UPDATE_LIST_ITEM_OBJECT_KEY_ON_INPUT_BLUR = "UPDATE_LIST_ITEM_OBJECT_KEY_ON_INPUT_BLUR";

